name: test

on:
# fired on branch main push
  push:
    branches:
      - main
# fired on branch main pull_request
  pull_request:
    branches:
      - main
# fired on schedule per 20 min
#   schedule:
#     - cron: '20 * * * *' #test per 20 min
  workflow_dispatch:
jobs: 
  # build job
  build:
    runs-on: ${{ matrix.os }} # run on spec os
    timeout-minutes: 10

    strategy:
      matrix:
        # set nodejs matrix
        node_version: [12.x, 14.x, 16.x]
        # set os matrix
        os: [ubuntu-latest, windows-latest, macos-latest]
        # architecture: [x86, x64]
        architecture: 
         - x64
      fail-fast: false

    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - name: sync git repo
        uses: actions/checkout@v3

      - name: install pnpm
        uses: pnpm/action-setup@v2 #https://github.com/pnpm/action-setup
        with:
          version: 6.34.0

      - name: set pnpm store directory
        run: pnpm config set store-dir ~/.pnpm-store
      # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

      - name: set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          cache: pnpm
    #   - name: run ci
    #     run: pnpm ci
      - name: run test
        run: pnpm test
    #   - uses: ymc-gitub/ymc-gitub@master
    #     with:
    #       WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
    #       GH_TOKEN: ${{ secrets.GH_TOKEN }}